accounts/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.edit import CreateView


urlpatterns = [
    path('signup/', CreateView.as_view(
        template_name='accounts/signup.html',
        form_class=UserCreationForm,
        success_url='/',
    ), name='signup'),
    path('login/', LoginView.as_view(
        redirect_authenticated_user=True,
        template_name='accounts/login.html'
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

config/urls.py
from wakes.views import top
from django.contrib import admin
from django.urls import path
from django.urls.conf import include



urlpatterns = [
    path('', top, name='top'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('wakes/', include('wakes.urls')),
    # member関係
    path('member/', include('member.urls')),
]

member/urls.py
from member.views import member_new, member_new, member_new_list, member_edit_list, member_delete_list, member_edit, member_delete, member
from django.urls import path

app_name = 'member'

urlpatterns = [
    #一覧
    path('', member, name="member"),

    # フォーム用ルーティング
    path('member_new_list', member_new_list, name="member_new_list"),
    path('edit/member_list', member_edit_list, name="member_edit_list"),
    path('delete/member_list', member_delete_list, name="member_delete_list"),

    # 実行用ルーティング
    path('member_new', member_new, name="member_new"),
    path('<int:member_id>/edit', member_edit, name="member_edit"),
    path('<int:member_id>/delete', member_delete, name="member_delete"),

]

wakes/urls.py
from wakes.views import wake_new, wake_detail, wake_edit, wake_classic, wake_delete
from django.urls import path

app_name = 'wakes'

urlpatterns = [
    # wake関係
    path('new/', wake_new, name='wake_new'),
    path('<int:wake_id>/', wake_detail, name='wake_detail'),
    path('<int:wake_id>/delete/', wake_delete, name='wake_delete'),
    path('<int:wake_id>/edit/', wake_edit, name='wake_edit'),

    # 簡易版ルーティング
    path('classic/', wake_classic, name='wake_classic'),

]

member/models.py
from django.db import models

# Create your models here.

wakes/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Member(models.Model):
    name = models.CharField('名前', max_length=12, blank=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="作成者", on_delete=models.CASCADE)

    class Meta:
        db_table = 'members'

    def __str__(self):
        return self.name


class Wake(models.Model):
    name = models.CharField('Wake名', max_length=50)
    description = models.CharField('説明', max_length=48, default='', null=False, blank=True)
    member = models.ManyToManyField(Member, related_name='members', related_query_name='member')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="作成者", on_delete=models.CASCADE)

    class Meta:
        db_table = 'wakes'

    def __str__(self):
        return self.name

member/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.http.response import HttpResponseForbidden
from wakes.form import MemberForm
from wakes.models import Member
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# member用View

# member一覧用View
@login_required
def member(request):
    user_id = request.user.id
    members = Member.objects.filter(created_by_id=user_id)
    members = members.order_by('name')
    context= {
        'members': members,
    }

    return render(request, 'member/member.html', context)


# フォームページ用View
@login_required
def member_new_list(request):
    form = MemberForm()
    user_id = request.user.id
    members = Member.objects.filter(created_by_id=user_id)
    members = members.order_by('name')
    context= {
        'members': members,
        'form': form,
    }

    return render(request, 'member/member_new_list.html', context)

@login_required
def member_edit_list(request):
    user_id = request.user.id
    members = Member.objects.filter(created_by_id=user_id)
    members = members.order_by('name')
    context= {
        'members': members,
    }

    return render(request, 'member/member_edit_list.html', context)

@login_required
def member_delete_list(request):
    user_id = request.user.id
    members = Member.objects.filter(created_by_id=user_id)
    members = members.order_by('name')
    context= {
        'members': members,
    }

    return render(request, 'member/member_delete_list.html', context)


# 実行用View
@login_required
def member_new(request):
    if request.method == 'POST':
        form = MemberForm(request.POST)
        if form.is_valid():
            member = form.save(commit=False)
            member.created_by = request.user
            member.save()
            return redirect(request.META.get('HTTP_REFERER'))
    else:
        return HttpResponseForbidden('正規の手続きを踏んでください')



@login_required
def member_edit(request, member_id):
    member = get_object_or_404(Member, pk=member_id)
    if member.created_by.id != request.user.id:
        return HttpResponseForbidden('このMemberの編集は許可されていません')
    
    if request.method == 'POST':
        form = MemberForm(request.POST, instance=member)
        if form.is_valid():
            form.save()
            return redirect('member:member_edit_list')
    else:
        form = MemberForm(instance=member)
    return render(request, 'member/member_edit.html', {'form': form})



@login_required
def member_delete(request, member_id):
    member = get_object_or_404(Member, pk=member_id)
    if member.created_by.id != request.user.id:
        return HttpResponseForbidden('このMemberの削除は許可されていません')
    
    member.delete()
    
    return redirect('member:member_delete_list')

wakes/views.py
from django import forms
from django.http.response import HttpResponseForbidden
from wakes.form import MemberForm, SelectMemberForm, WakeForm
from wakes.models import Member, Wake
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required


# Create your views here.
# トップページ用View
def top(request):
    wakes = Wake.objects.all().order_by('-id')
    context = {
        'wakes': wakes,
    }
    return render(request, 'wakes/top.html', context)

# wake用View
@login_required
def wake_new(request):
    if request.method == 'POST':
        form = WakeForm(request.POST)
        if form.is_valid():
            wake = form.save(commit=False)
            wake.created_by = request.user
            wake.save()
            return redirect(top)
    else:
        form = WakeForm()
    return render(request, 'wakes/wake_new.html', {'form': form})

@login_required
def wake_edit(request, wake_id):
    wake = get_object_or_404(Wake, pk=wake_id)
    form_add = MemberForm()
    if wake.created_by.id != request.user.id:
        return HttpResponseForbidden('このWakeの編集は許可されていません')
    
    if request.method == 'POST':
        form = SelectMemberForm(request.POST, instance=wake)
        if form.is_valid():
            form.save()
            return redirect('wakes:wake_detail', wake_id)
    else:
        form = SelectMemberForm(instance=wake)
    return render(request, 'wakes/wake_edit.html', {
        'wake': wake,
        'form': form,
        'form_add': form_add,
    })

@login_required
def wake_detail(request, wake_id):
    wake = get_object_or_404(Wake, pk=wake_id)

    if wake.created_by.id != request.user.id:
        return HttpResponseForbidden('このWakeの閲覧は許可されていません')

    context= {
        'wake': wake,
    }

    return render(request, 'wakes/wake_detail.html', context)

def wake_classic(request):
    return render(request, 'wakes/wake_classic.html')

@login_required
def wake_delete(request, wake_id):
    wake = get_object_or_404(Wake, pk=wake_id)

    if wake.created_by.id != request.user.id:
        return HttpResponseForbidden('このWakeの削除は許可されていません')
    
    wake.delete()
    
    return redirect('top')

templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block main %}
  <h1>ログイン</h1>

  <form action="" method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="ログイン" %}
  </form>
{% endblock main %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block main %}
  <h1>新規登録</h1>

  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="登録" %}
  </form>
{% endblock main %}

templates/base.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="UTF-8">
    <title>Team-Wakes</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'wakes/css/style.css' %}">
    {% block exheader %}{% endblock exheader%}
  </head>

  <body>
    <nav class="navbar navbar-expand flex-md-row navbar-dark bg-dark">
      <div class="container justify-content-between">
        <a class="navbar-brand" href="/">Team-Wakes</a>
        <ul class="navbar-nav mr-md-2">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link">{{ user.username }}</a>
              <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">ログイン</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">会員登録</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <main>
      <div class="container">
        {% block main %}{% endblock main %}
      </div>
    </main>
    
  </body>

</html>

templates/member/member.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
  <div class="sub-welcome">
    <h1 class="title">Team-Wakes</h1>
    <p class="subtitle">メンバー一覧</p>
  </div>
  <div class="content">
    <div class="all-member-list">
      <h2 class="content-head">Member-list</h2>
      <ul class="member-list-ul">
        {% for member in members %}
          <li class="member-list">{{ member.name }}</li>
        {% endfor %}
      </ul>
    </div>
    <div class="function-container">
      <h2 class="content-head">Editor</h2>
      <a class="btn btn-color btn-function" href="{% url 'member:member_new_list' %}">Add</a>
      <br>
      <a class="btn btn-color btn-function" href="{% url 'member:member_edit_list' %}">Edit</a>
      <br>
      <a class="btn btn-color btn-function" href="{% url 'member:member_delete_list' %}">Delete</a>
      <br>
      <a class="btn btn-color btn-function" href="{% url 'top' %}">Top-Page</a>
    </div>
  </div>
{% endblock main %}

templates/member/member_delete_list.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
  <div class="sub-welcome">
    <h1 class="title">Team-Wakes</h1>
    <p class="subtitle">メンバーの削除</p>
  </div>
  <div class="content">
    <div class="all-member-list">
      <h2 class="content-head">Member-list</h2>
      <ul class="member-list-ul">
        {% for member in members %}
          <li class="member-list">
            <a href="{% url 'member:member_delete' member.id %}" class="wake">
              {{ member.name }}
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="function-container">
      <h2 class="content-head">menu</h2>
      <a class="btn btn-color btn-function" href="{% url 'member:member' %}">メンバー一覧へ</a>
      <br>
      <a class="btn btn-color btn-function" href="{% url 'member:member_new_list' %}">追加画面へ</a>
      <br>
      <a class="btn btn-color btn-function" href="{% url 'member:member_edit_list' %}">編集画面へ</a>
      <br>
      <a class="btn btn-color btn-function" href="{% url 'top' %}">Top-Page</a>
    </div>
  </div>
{% endblock main %}

templates/member/member_edit.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block main %}
  <h1>Memberの編集</h1>
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit"  class="btn btn-classic width-50">
        save
      </button>
  </form>
{% endblock main %}

templates/member/member_edit_list.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
  <div class="sub-welcome">
    <h1 class="title">Team-Wakes</h1>
    <p class="subtitle">メンバー名の編集</p>
  </div>
  <div class="content">
    <div class="all-member-list">
      <h2 class="content-head">Member-list</h2>
      <ul class="member-list-ul">
        {% for member in members %}
          <li class="member-list">
            <a href="{% url 'member:member_edit' member.id %}" class="wake">
              {{ member.name }}
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="function-container">
      <h2 class="content-head">menu</h2>
      <a class="btn btn-color btn-function" href="{% url 'member:member' %}">メンバー一覧へ</a>
      <br>
      <a class="btn btn-color btn-function" href="{% url 'member:member_new_list' %}">追加画面へ</a>
      <br>
      <a class="btn btn-color btn-function" href="{% url 'member:member_delete_list' %}">削除画面へ</a>
      <br>
      <a class="btn btn-color btn-function" href="{% url 'top' %}">Top-Page</a>
    </div>
  </div>
{% endblock main %}

templates/member/member_new.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block main %}
  <h1>Memberの登録</h1>
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="btn-container">
      <button type="submit" value="add" class="btn btn-classic width-50">
        Add
      </button>
      <button type="submit" value="back" class="btn btn-classic width-50">
        <a href="{% url 'member' %}">
          Back
        </a>
      </button>
    </div>
  </form>
  <h2 class="content-head">Member-list</h2>
  <div class="all-member-list-for-edit">

    <ul>
      {% for member in members %}
        <li class="member-list">{{ member.name }}</li>
      {% endfor %}
    </ul>
  </div>
{% endblock main %}

templates/member/member_new_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block main %}
  <h1>Memberの登録</h1>
  <form action="{% url 'member:member_new' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="btn-container">
      <button type="submit" value="add" class="btn btn-classic width-50">
        Add
      </button>
      <button type="submit" value="back" class="btn btn-classic width-50">
        <a href="{% url 'member:member' %}">
          メンバー一覧へ
        </a>
      </button>
    </div>
  </form>
  <h2 class="content-head">Member-list</h2>
  <div class="all-member-list-for-edit">

    <ul>
      {% for member in members %}
        <li class="member-list">{{ member.name }}</li>
      {% endfor %}
    </ul>
  </div>
{% endblock main %}

templates/top.html
{% extends 'base.html' %}

{% block main %}
  <div class="welcome">
    <h1 class="title">ようこそ、Team-Wakeへ！</h1>
    <p class="subtitle">チームをわけわけしましょう！</p>
    <a class="btn btn-primary" href="{% url 'member_new' %}">メンバーを登録する</a>
  </div>

  {% if snippets %}
    <table class="table">
      <thead>
        <tr>
          <th>投稿者</th>
          <th>投稿日</th>
          <th>タイトル</th>
        </tr>
      </thead>
      <tbody>
        {% for snippet in snippets %}
          <tr>
            <th>{{ snippet.created_by.username }}</th>
            <th>{{ snippet.created_at }}</th>
            <th>
              <a href="{% url 'snippet_detail' snippet.id %}">
                {{ snippet.title }}
              </a>
            </th>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>スニペットはまだ投稿されていません.</p>
  {% endif %}
{% endblock main %}

templates/wakes/detailing.html
{% extends 'base.html' %}
{% load static %}

{% block exheader %}
<script src="{% static 'wakes/js/main.js' %}"></script>
{% endblock exheader %}

{% block main %}
  <div class="sub-welcome">
    <h1 class="title">{{ wake.name }}</h1>
    <p class="subtitle">{{ wake.description }}</p>
  </div>
  <div class="content">
    <div class="team-a">
      <ul class="team-ul" id="ul-team-a">
      <li class="content-header">team A</li>
      </ul>
    </div>
    <div class="member">
      {% if wake.member %}
        <ul class="member-ul">
          <li class="content-header">member</li>
          {% for member in members %}
            <li>{{ wake.member }}</li>
          {% endfor %}
        </ul>
    {% endif %}
    </div>
    <div class="team-b">
      <ul class="team-ul" id="ul-team-b">
      <li class="content-header">team B</li>
      <li>b</li>
      <li>b</li>
      <li>b</li>
      <li>b</li>
      <li>b</li>
      <li class="member-list"><button>b to a</button></li>
      </ul>
    </div>
  </div>
{% endblock main %}

templates/wakes/member.html
{% extends 'base.html' %}
{% load static %}


{% block main %}
  <div class="sub-welcome">
    <h1 class="title">Team-Wakes</h1>
    <p class="subtitle">メンバーの編集</p>
  </div>
  <div class="content">
    <div class="all-member-list">
      <h2 class="content-head">Member-list</h2>
      <ul>
      {% for member in members %}
        <li class="member-list">{{ member.name }}</li>
      {% endfor %}
      </ul>
    </div>
    <div class="function-container">
      <h2 class="content-head">Editor</h2>
        <a class="btn btn-color btn-function">Add</a>
        <br>
        <a class="btn btn-color btn-function">Edit</a>
        <br>
        <a class="btn btn-color btn-function">Delete</a>
    </div>
  </div>
{% endblock main %}

templates/wakes/top.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
  <div class="welcome">
    <h1 class="title">ようこそ、Team-Wakesへ！</h1>
    <p class="subtitle">チームをわけわけしましょう！</p>
    {% if user.is_authenticated %}
      <div class="function-bar">
        <a class="btn btn-color" href="{% url 'wakes:wake_new' %}">Wakesの登録</a>
        <a class="btn btn-color" href="{% url 'member:member' %}">メンバー一覧</a>
      </div>
    {% else %}
      <a class="btn btn-color" href="{% url 'login' %}">ログイン</a>
    {% endif %}

  </div>

  {% if user.is_authenticated %}
    {% if wakes %}
      <ul class="wakes-list">
        <li class="wakes-header">Wakes一覧</li>
        {% for wake in wakes %}
          {% if wake.created_by.id == user.id %}
            <li>
              <a href="{% url 'wakes:wake_detail' wake.id %}" class="wake">
                {{ wake.name }}
              </a>
            </li>
          {% endif %}
        {% endfor %}
      </ul>
    {% else %}
      <p class="message">Wakeはまだありません.</p>
    {% endif %}
  {% else %}
    <div class="welcome">
      <a class="btn btn-color" href="{% url 'wakes:wake_classic' %}">簡易版を利用する</a>
    </div>
  {% endif %}
{% endblock main %}

templates/wakes/wake_classic.html
{% extends 'base.html' %}
{% load static %}

{% block exheader %}
  <script src="{% static 'wakes/js/main.js' %}"></script>
{% endblock exheader %}

{% block main %}
  <div class="sub-welcome">
    <h1 class="title">Team-Wakes</h1>
    <p class="subtitle">改行区切りでメンバーを入力してください</p>
  </div>
  <div class="content">
    <div class="team-a">
      <h2 class="content-head">team A</h2>
      <ol id="team_a" class="team-container"></ol>
    </div>

    <div class="member">
      <h2 class="content-head">member</h2>
      <form action="" method="post">
        {% csrf_token %}
        <textarea name="classic-member" id="classic-member" rows="14" class="classic-member">
        メンバー1&#13;
        メンバー2&#13;
        メンバー3&#13;
        メンバー4&#13;
        メンバー5&#13;
        メンバー6&#13;
        メンバー7&#13;
        メンバー8&#13;
        メンバー9&#13;
        メンバー10&#13;
        メンバー11&#13;
        メンバー12&#13;
        </textarea>
        <button type="button" value="Wake!" class="btn btn-color btn-classic" onclick="wakeTeam()">Wake!</button>
      </form>
    </div>

    <div class="team-b">
      <h2 class="content-head">team B</h2>
      <ol id="team_b" class="team-container"></ol>
    </div>
  </div>
{% endblock main %}

templates/wakes/wake_detail.html
{% extends 'base.html' %}
{% load static %}

{% block exheader %}
  <script src="{% static 'wakes/js/wakes.js' %}"></script>
{% endblock exheader %}

{% block main %}
  <div class="sub-welcome">
    <h1 class="title">{{ wake.name }}</h1>
    <p class="subtitle">{{ wake.description }}</p>
    <a class="btn btn-color" href="{% url 'wakes:wake_edit' wake.id %}">Memberの変更</a>
  </div>
  <div class="content">
    <div class="team-a">
      <h2 class="content-head">team A</h2>
      <ol id="team_a" class="team-container"></ol>
    </div>

    <div class="member">
      <h2 class="content-head">member</h2>
      <div class="member-container">
        <ul class="member-list-ul">
          <form name="member-form">
            {% for member in wake.member.all %}
                <li class="label">
                  <input type="checkbox" name="selected-member" id="{{ member.name }}" value="{{ member.name }}" checked>
                  <label for="{{ member.name }}">{{ member.name }}</label>
                </li>
            {% endfor %}
          </form>
        </ul>
      </div>
      <button type="button" value="Wake!" class="btn btn-color btn-classic" id="try-js" onclick="wakeTeam()">Wake!</button>
    </div>

    <div class="team-b">
      <h2 class="content-head">team B</h2>
      <ol id="team_b" class="team-container"></ol>
    </div>
  </div>
{% endblock main %}

templates/wakes/wake_edit.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block main %}
  <h1>Memberの編集</h1>
  <div class="content">
    <div class="all-member-list">
      <form action="" method="post">
        {% csrf_token %}
        <div class="member-list-form">
          {% bootstrap_form form %}
        </div>
        <input type="hidden" value="{{ wake.id }}">
        <button type="submit" class="btn btn-classic width-50">
          更新
        </button>
      </form>
    </div>
    <div class="function-container">
      <form action="{% url 'member:member_new' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form_add %}
        <div class="btn-container">
          <button type="submit" value="add" class="btn btn-classic width-50">
            Add
          </button>
        </div>
      </form>
    </div>
  </div>
{% endblock main %}

templates/wakes/wake_new.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block main %}
  <h1>Wakeの登録</h1>
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit"  class="btn btn-classic width-50">
        Add
      </button>
  </form>
{% endblock main %}

templates/wakes/wakes_new.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block main %}
  <h1>Wakeの登録</h1>
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type='submit' content='登録' %}
  </form>
{% endblock main %}